{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ark
  labels:
    chart: {{ template "ark-server.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ template "ark-server.name" . }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Values.namespace.name }}
    name: {{ template "ark-server.serverServiceAccount" . }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
    chart: {{ template "ark-server.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ template "ark-server.name" . }}
  name: deploy-ark
rules:
  - apiGroups: ['ark.heptio.com']
    verbs: ["*"]
    resources: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: deploy-ark
  labels:
    chart: {{ template "ark-server.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ template "ark-server.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deploy-ark
subjects:
  - kind: ServiceAccount
    name: {{ template "ark-server.hookServiceAccount" . }}
    namespace: {{ .Values.namespace.name }}
{{- end }}
