---
apiVersion: ark.heptio.com/v1
kind: Config
metadata:
  namespace: {{ .Values.namespace.name }}
  name: default
persistentVolumeProvider:
  name: {{ required "PLEASE SET VALUE" .Values.configuration.cloudprovider  }}
  config:
    {{- if eq .Values.configuration.cloudprovider "gcp" }}
    project: {{ required "PLEASE SET VALUE" .Values.configuration.project  }}
    {{- else if eq .Values.configuration.cloudprovider "aws" }}
    region: {{ required "PLEASE SET VALUE" .Values.configuration.region  }}
    {{- end }}
backupStorageProvider:
  name: {{ required "PLEASE SET VALUE" .Values.configuration.cloudprovider  }}
  bucket: {{ required "PLEASE SET VALUE" .Values.configuration.bucket  }}
  {{- if eq .Values.configuration.cloudprovider "aws" }}
  config:
    region: {{ required "PLEASE SET VALUE" .Values.configuration.region  }}
  {{- end }}
backupSyncPeriod: {{ .Values.configuration.backupSyncPeriod }}
gcSyncPeriod: {{ .Values.configuration.gcSyncPeriod }}
scheduleSyncPeriod: {{ .Values.configuration.scheduleSyncPeriod }}
restoreOnlyMode: {{ .Values.configuration.restoreOnlyMode }}

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace.name }}
  name: ark
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: ark
    spec:
      restartPolicy: Always
      serviceAccountName: ark
      containers:
        - name: ark
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /ark
          args:
            - server
          volumeMounts:
            - name: cloud-credentials
              mountPath: /credentials
            - name: plugins
              mountPath: /plugins
          env:
            - name: {{ required "PLEASE CHANGE VALUE" .Values.configuration.credentials }}
              value: /credentials/cloud
      volumes:
        - name: cloud-credentials
          secret:
            secretName: {{ .Values.secret.name }}
        - name: plugins
          emptyDir: {}
