apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace.server.name }}
  name: ark
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: ark
    spec:
      restartPolicy: Always
      serviceAccountName: {{ template "ark-server.sa" . }}
      containers:
        - name: ark
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /ark
          args:
            - server
            - --namespace
            - {{ .Values.namespace.backup.name }}
          volumeMounts:
            - name: cloud-credentials
              mountPath: /credentials
            - name: plugins
              mountPath: /plugins
          env:
            - name: {{ required "PLEASE CHANGE VALUE" .Values.configuration.credentials }}
              value: /credentials/cloud
      volumes:
        - name: cloud-credentials
          secret:
            secretName: {{ .Values.secret.name }}
        - name: plugins
          emptyDir: {}
