apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: {{ .Values.namespace.server.name }}
  name: {{ template "ark-server.fullname" . }}
  release: {{ .Release.Name }}
  app: {{ template "ark-server.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ark
      release: {{ .Release.Name }}
      app: {{ template "ark-server.name" . }}
  template:
    metadata:
      labels:
        component: ark
        release: {{ .Release.Name }}
        app: {{ template "ark-server.name" . }}
    spec:
      restartPolicy: Always
      serviceAccountName: {{ template "ark-server.sa" . }}
      containers:
        - name: ark
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - /ark
          args:
            - server
            - --namespace
            - {{ .Values.namespace.backup.name }}
          volumeMounts:
            - name: cloud-credentials
              mountPath: /credentials
            - name: plugins
              mountPath: /plugins
          env:
            - name: {{ .Values.configuration.credentials }}
              value: /credentials/cloud
      volumes:
        - name: cloud-credentials
          secret:
            secretName: {{ .Values.secret.name }}
        - name: plugins
          emptyDir: {}
