{{- if .Values.serviceAccount.server.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ark-server.sa" . }}
  namespace: {{ .Values.namespace.server.name }}
  labels:
    component: ark
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ template "ark-server.name" . }}
{{- end }}

{{- if .Values.rbac.create }}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ark
  labels:
    component: ark
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ template "ark-server.name" . }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Values.namespace.server.name }}
    name: {{ template "ark-server.sa" . }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}

